name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  CI: true

jobs:
  lint:
    uses: haraka/.github/.github/workflows/lint.yml@master
    permissions:
      contents: read

  ubuntu:
    needs: [lint]
    uses: haraka/.github/.github/workflows/ubuntu.yml@master
    permissions:
      contents: read

  windows:
    needs: [lint]
    uses: haraka/.github/.github/workflows/windows.yml@master
    permissions:
      contents: read
    if: ${{ false }} # disabled, until Redis for GHA Windows exists
